### PR TITLE
Saving few bytes for browser

### PR DESCRIPTION
**Pull request by abhijeetkpawar**
1. Cached `this` in variable
2. Combined  `var` statements

### CODE REVIEW

**Comment by stefanpenner** [comment]
> Combined var statements

doesn't the minifier do this already?

> Cached this in variable

nice

**Comment by abhijeetkpawar** [comment]
Minifier can do that, but having one var looks more readable.

**Comment by stefanpenner** [comment]
> but having one var looks more readable.

I would prefer this remained as it did before.

**Comment by abhijeetkpawar** [comment]
Will raise a new request without any change in var declarations

**Pull request closed without merging**
