### PR TITLE
check exports before amd in case mixed environment

### PR DESCRIPTION
**Pull request by liquidg3**
I am using AMD inside of Node (not a fan of require). Unfortunately, simply requiring the mongodb module broke my app because the mongodb library tries to include the es6-promise library using require but es6-promise checks define() && AMD first.

By checking exports first (and AMD second) I make sure that the library works in mixed AMD/Require environments more reliably.

Now, I know I have broken the ability to use AMD to include the library when in a mixed environment (since it's checking exports first now, which is arguably just the opposite of the problem that currently exists), but given that every library in node uses require, the situation I'm facing will happen 9 out of 10 times, which is that some 3rd party is using require to load it and it's instead trying to use define();

So, while there is no 100% solution for making it automagically determine the environment when the environment is mixed, require is more popular and so checking that first will mean the it works in the majority of cases.

Thoughts?

### CODE REVIEW

**Comment by stefanpenner** [comment]
@liquidg3 hmm, this doesn't appear bad, but I'm unsure if this will now break users that expect the reverse

**Comment by liquidg3** [comment]
Honestly, I could be fine. It seems legit to me, but I feel like every time I think that something blows up in my face!

**Comment by stefanpenner** [comment]
Ya. My thoughts as well.  Hmmm... 

I mean, we can try it and see.

**Comment by stefanpenner** [comment]
Thinking about this further, wouldn't this break for literally any UMD you use?

**Comment by liquidg3** [comment]
Shoot, not sure. I’m so immersed in what I’m doing I can’t see beyond it. We can probably just hang tight until someone wants to test.

**Comment by stefanpenner** [comment]
I believe we should keep the existing UMD header, unless this is a common trend for all libraries UMD to do something else.

I do feel your pain, but I suspect merging this will just trade one set of issues for another. We can revisit if someone can demonstrate my concerns to be not-important.

**Comment by booya2nd** [comment]
+1 
Ran into the same issue today - we are not using AMD explicitily  - but as a third party library we are being "required" as AMD module which breaks the customer's website. the proposed fixed would fixe the issue

**Comment by bra1n** [comment]
I agree, and would like to add: why not have both? If an environment has both AMD and UMD, why don't you simply use both of them?

**Pull request closed without merging**
