### PR TITLE
Ignore dist/test on npm

### PR DESCRIPTION
**Pull request by TrySound**
package.json files overrides .npmignore

### CODE REVIEW

**Comment by TrySound** [comment]
fix #130

**Comment by stefanpenner** [comment]
LGTM

**Comment by TrySound** [comment]
Make patch release, please.

**Comment by stefanpenner** [comment]
@TrySound thank you kindly, sorry for letting this linger. 

its release as v3.0.1

**Comment by TrySound** [comment]
@stefanpenner Thanks!

**Pull request merged**
