### PR TITLE
Ability to override the internal asap implementation

### PR DESCRIPTION
**Pull request by vicb**
This feature was missing from my previous PR and is needed for Angular2.

Context:
We need to know when there are pending microtasks. Before this PR, Promises would call `asap()` to schedule microtasks but we have no way to know that the function has been called.

In angular, the idea is to re-route `asap()` to `zone.scheduleMicrotask()`. `zone.scheduleMicrotask()` would then use the original asap implementation `ES6Promise._asap` to schedule microtasks.

reference (full stack test)
- https://github.com/angular/zone.js/pull/103 is the PR on zone.js to use this feature,
- https://github.com/angular/angular/pull/1981 is the PR on angular

@jakearchibald if you are ok with the changes, it would be great to release 2.3.0 (see the last commit). Sorry for having missed that in my first PR.

### CODE REVIEW

**Comment by stefanpenner** [comment]
If set asap exists. Why do we need set scheduler?

**Comment by vicb** [comment]
asap wraps the queue logic and call one of the scheduler method.

With this change I use both:
- [`Promise._setAsap`](https://github.com/vicb/zone.js/commit/685174ed5c09a4867da1521f4b95d7c7233bb013#diff-655bab2d2c559f7c4e83b01699f9a331R7) is called to route all microtask to zone.scheduleMicrotask,
- [`Promise._setScheduler`](https://github.com/vicb/zone.js/commit/685174ed5c09a4867da1521f4b95d7c7233bb013#diff-655bab2d2c559f7c4e83b01699f9a331R39) is used to add a native Promise based scheduler method when available.

Do you think I should try to simplify the implementation ?

**Comment by stefanpenner** [comment]
> Do you think I should try to simplify the implementation ?

isn't setAsap a superset?

**Comment by vicb** [comment]
Yes but if we remove the ability to `_setScheduler()` then I need to copy the es6-promise implementation of asap in zone.js in order to customize this.

Below is the control flow (not sure if it helps...)

```
asap (of es6-promise, overriden via es6Promise._setAsap)
 |
 | calls
 |
 ----> zone.js scheduleMicrotasks() - zone.js has hooks here
             |
             | calls
             |
             ----> es6Promise._asap() - schedule microtasks
                           |
                           | calls
                           |
                           -----> the custom scheduler fn or any of the built-in mechanism
```

**Comment by stefanpenner** [comment]
> Yes but if we remove the ability to _setScheduler() then I need to copy the es6-promise implementation of asap in zone.js in order to customize this.

ah ok

**Comment by vicb** [comment]
@stefanpenner thanks !

@jakearchibald could you please release 2.3.0 ?

**Pull request merged**
